# Generated by Django 4.0.5 on 2022-07-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='feita',
            field=models.BooleanField(default=True),
        ),
    ]
