# Generated by Django 4.0.5 on 2022-07-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_feita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='feita',
            field=models.BooleanField(default=False),
        ),
    ]
