name: Aplicação Django

on: [push]

env:
  install:
    - cp contrib/env-sample .env
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest 
    - name: Rodar testes automáticos
      run: pytest webdev tarefas
